FROM node:18-bullseye-slim

WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install
# COPY . .

# WORKDIR /app/frontend
# RUN npm run build
# CMD ["npm", "run", "start"]
