services:
  frontend:
    build:
      context: .
      dockerfile: frontend/.devcontainer/Dockerfile
    # command: npm run start
    command: sleep infinity
    depends_on:
      - backend
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
  backend:
    build:
      context: .
      dockerfile: backend/.devcontainer/Dockerfile
    # command: npm run start
    # command: cargo run
    command: sleep infinity
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - 4000:3000
    volumes:
      - .:/app:cached
  mysql:
    image: mysql:8
    env_file:
      - .env
    command: mysqld --default_authentication_plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
      retries: 3
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  schemaspy:
    build:
      dockerfile: schemaspy/Dockerfile
    command: java -jar schemaspy.jar
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./schemaspy/schemaspy.properties:/app/schemaspy.properties
      - ./schemaspy/output:/output
volumes:
  mysql-data:
